"""Descripción de tus cambios

Revision ID: 51af05b0bf33
Revises: 
Create Date: 2025-11-05 12:16:05.146058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51af05b0bf33'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_station_data', 'solar_panel')
    op.drop_column('weather_station_data', 'low_battery')
    op.drop_column('weather_station_data', 'observations')
    op.drop_column('weather_station_data', 'active_sensor')
    op.drop_column('weather_station_data', 'open_door')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_station_data', sa.Column('open_door', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('weather_station_data', sa.Column('active_sensor', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('weather_station_data', sa.Column('observations', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('weather_station_data', sa.Column('low_battery', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('weather_station_data', sa.Column('solar_panel', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
